#!/bin/bash

# Firebase Test Data Setup Script
# This script helps set up test data in Firestore

echo "🔧 Firebase Test Data Setup"
echo "================================"
echo ""
echo "This script will help you set up test data in Firestore."
echo "Make sure you are logged in to Firebase first:"
echo ""
echo "  firebase login"
echo ""
echo "================================"
echo ""

# Check if firebase CLI is installed
if ! command -v firebase &> /dev/null; then
    echo "❌ Firebase CLI not found. Install it first:"
    echo "   npm install -g firebase-tools"
    exit 1
fi

echo "📋 To set up test data manually:"
echo ""
echo "1. Go to https://console.firebase.google.com"
echo "2. Select your project"
echo "3. Click 'Firestore Database' in the left sidebar"
echo "4. Click 'Create Database'"
echo "5. Add these collections:"
echo ""
echo "---"
echo "COLLECTION: users"
echo ""
echo "Add two documents:"
echo ""
echo "Document 1 - Student"
echo "  ID: student@example.com (or auto ID)"
echo "  Data:"
echo "  {"
echo "    \"email\": \"student@example.com\","
echo "    \"name\": \"John Student\","
echo "    \"role\": \"student\""
echo "  }"
echo ""
echo "Document 2 - Teacher"
echo "  ID: teacher@example.com (or auto ID)"
echo "  Data:"
echo "  {"
echo "    \"email\": \"teacher@example.com\","
echo "    \"name\": \"Jane Teacher\","
echo "    \"role\": \"teacher\""
echo "  }"
echo ""
echo "---"
echo "COLLECTION: student_progress"
echo ""
echo "Add document:"
echo "  ID: (same as student's Auth UID)"
echo "  Data:"
echo "  {"
echo "    \"ankle\": 45,"
echo "    \"knee\": 60,"
echo "    \"terminology\": 30,"
echo "    \"userId\": \"(student-auth-uid)\","
echo "    \"createdAt\": timestamp"
echo "  }"
echo ""
echo "---"
echo ""
echo "✅ After setting up the data:"
echo ""
echo "1. Create Authentication accounts:"
echo "   - Go to Authentication → Users"
echo "   - Click 'Create user'"
echo "   - Create: student@example.com / password"
echo "   - Create: teacher@example.com / password"
echo ""
echo "2. Deploy to Firebase:"
echo "   firebase deploy --only hosting"
echo ""
echo "3. Visit your hosting URL and log in"
echo ""
echo "================================"
echo ""
echo "Need help? Check FIREBASE_DEPLOYMENT_GUIDE.md"
